/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	float a;
	float b;
};
typedef struct numeros numeros;

#define OPERACIONES_PROG 0x20000001
#define OPERACIONES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  float * suma_1(numeros *, CLIENT *);
extern  float * suma_1_svc(numeros *, struct svc_req *);
#define RESTA 2
extern  float * resta_1(numeros *, CLIENT *);
extern  float * resta_1_svc(numeros *, struct svc_req *);
#define MULTIPLICACION 3
extern  float * multiplicacion_1(numeros *, CLIENT *);
extern  float * multiplicacion_1_svc(numeros *, struct svc_req *);
#define DIVISION 4
extern  float * division_1(numeros *, CLIENT *);
extern  float * division_1_svc(numeros *, struct svc_req *);
extern int operaciones_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  float * suma_1();
extern  float * suma_1_svc();
#define RESTA 2
extern  float * resta_1();
extern  float * resta_1_svc();
#define MULTIPLICACION 3
extern  float * multiplicacion_1();
extern  float * multiplicacion_1_svc();
#define DIVISION 4
extern  float * division_1();
extern  float * division_1_svc();
extern int operaciones_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);

#else /* K&R C */
extern bool_t xdr_numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
