/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIZ3_H_RPCGEN
#define _MATRIZ3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct matrices3 {
	int n;
	int fila_inicio;
	int fila_fin;
	int A[100];
	int B[100];
};
typedef struct matrices3 matrices3;

struct resultado3 {
	int n;
	int fila_inicio;
	int fila_fin;
	int C[100];
};
typedef struct resultado3 resultado3;

#define MATRIZ_PROG3 0x20000003
#define MATRIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLICAR3 1
extern  resultado3 * multiplicar3_1(matrices3 *, CLIENT *);
extern  resultado3 * multiplicar3_1_svc(matrices3 *, struct svc_req *);
extern int matriz_prog3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLICAR3 1
extern  resultado3 * multiplicar3_1();
extern  resultado3 * multiplicar3_1_svc();
extern int matriz_prog3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrices3 (XDR *, matrices3*);
extern  bool_t xdr_resultado3 (XDR *, resultado3*);

#else /* K&R C */
extern bool_t xdr_matrices3 ();
extern bool_t xdr_resultado3 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIZ3_H_RPCGEN */
