/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "matriz2.h"

bool_t
xdr_matrices2 (XDR *xdrs, matrices2 *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (3 +  10000  + 10000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_inicio))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_fin))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->A, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->B, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->n);
			IXDR_PUT_LONG(buf, objp->fila_inicio);
			IXDR_PUT_LONG(buf, objp->fila_fin);
			{
				register int *genp;

				for (i = 0, genp = objp->A;
					i < 10000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->B;
					i < 10000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (3 +  10000  + 10000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_inicio))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_fin))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->A, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->B, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->n = IXDR_GET_LONG(buf);
			objp->fila_inicio = IXDR_GET_LONG(buf);
			objp->fila_fin = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->A;
					i < 10000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				register int *genp;

				for (i = 0, genp = objp->B;
					i < 10000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fila_inicio))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fila_fin))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->A, 10000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->B, 10000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado2 (XDR *xdrs, resultado2 *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (3 +  10000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_inicio))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_fin))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->C, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->n);
			IXDR_PUT_LONG(buf, objp->fila_inicio);
			IXDR_PUT_LONG(buf, objp->fila_fin);
			{
				register int *genp;

				for (i = 0, genp = objp->C;
					i < 10000; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (3 +  10000 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->n))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_inicio))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fila_fin))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->C, 10000,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->n = IXDR_GET_LONG(buf);
			objp->fila_inicio = IXDR_GET_LONG(buf);
			objp->fila_fin = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->C;
					i < 10000; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fila_inicio))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fila_fin))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->C, 10000,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
