/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "matriz3.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

resultado3 *
multiplicar3_1(matrices3 *argp, CLIENT *clnt)
{
	static resultado3 clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MULTIPLICAR3,
		(xdrproc_t) xdr_matrices3, (caddr_t) argp,
		(xdrproc_t) xdr_resultado3, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
