/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIZ2_H_RPCGEN
#define _MATRIZ2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct matrices2 {
	int n;
	int fila_inicio;
	int fila_fin;
	int A[100];
	int B[100];
};
typedef struct matrices2 matrices2;

struct resultado2 {
	int n;
	int fila_inicio;
	int fila_fin;
	int C[100];
};
typedef struct resultado2 resultado2;

#define MATRIZ_PROG2 0x20000002
#define MATRIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLICAR2 1
extern  resultado2 * multiplicar2_1(matrices2 *, CLIENT *);
extern  resultado2 * multiplicar2_1_svc(matrices2 *, struct svc_req *);
extern int matriz_prog2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLICAR2 1
extern  resultado2 * multiplicar2_1();
extern  resultado2 * multiplicar2_1_svc();
extern int matriz_prog2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrices2 (XDR *, matrices2*);
extern  bool_t xdr_resultado2 (XDR *, resultado2*);

#else /* K&R C */
extern bool_t xdr_matrices2 ();
extern bool_t xdr_resultado2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIZ2_H_RPCGEN */
