/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIZ_H_RPCGEN
#define _MATRIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_N 1500
#define MAX_ELEM 2250000

struct matrices1 {
	int n;
	int fila_inicio;
	int fila_fin;
	int A[MAX_ELEM];
	int B[MAX_ELEM];
};
typedef struct matrices1 matrices1;

struct resultado1 {
	int n;
	int fila_inicio;
	int fila_fin;
	int C[MAX_ELEM];
};
typedef struct resultado1 resultado1;

#define MATRIZ_PROG1 0x20000001
#define MATRIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLICAR1 1
extern  resultado1 * multiplicar1_1(matrices1 *, CLIENT *);
extern  resultado1 * multiplicar1_1_svc(matrices1 *, struct svc_req *);
extern int matriz_prog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLICAR1 1
extern  resultado1 * multiplicar1_1();
extern  resultado1 * multiplicar1_1_svc();
extern int matriz_prog1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrices1 (XDR *, matrices1*);
extern  bool_t xdr_resultado1 (XDR *, resultado1*);

#else /* K&R C */
extern bool_t xdr_matrices1 ();
extern bool_t xdr_resultado1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIZ_H_RPCGEN */
