/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATRIZ_H_RPCGEN
#define _MATRIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct matrices {
	int n;
	int fila_inicio;
	int fila_fin;
	int A[4];
	int B[4];
};
typedef struct matrices matrices;

struct resultado {
	int n;
	int fila_inicio;
	int fila_fin;
	int C[4];
};
typedef struct resultado resultado;

#define MATRIZ_PROG1 0x20000001
#define MATRIZ_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MULTIPLICAR1 1
extern  resultado * multiplicar1_1(matrices *, CLIENT *);
extern  resultado * multiplicar1_1_svc(matrices *, struct svc_req *);
extern int matriz_prog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MULTIPLICAR1 1
extern  resultado * multiplicar1_1();
extern  resultado * multiplicar1_1_svc();
extern int matriz_prog1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_matrices (XDR *, matrices*);
extern  bool_t xdr_resultado (XDR *, resultado*);

#else /* K&R C */
extern bool_t xdr_matrices ();
extern bool_t xdr_resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATRIZ_H_RPCGEN */
